### ISSUE TITLE
Forking vs. contributing here

### ISSUE THREAD

**Issue by albacoretuna** [romanmatiasko/reti-chess#13]
Hi, 
I really enjoyed using Reti. However there some things that need improvement. So I was thinking to ask your opinion about these two options:
- I can fork, develop and make my own version of this project
- I can become a contributor to your repo and move your repo forward

I know based on the licence you've granted everyone to do the first one, but I wanted to see which one you prefer. And also I don't like sending pull requests that get nowhere.

**Comment by romanmatiasko** [comment]
Yeah, there are many things that could be improved. I'm not longer developing this app, but I don't mind merging some PRs if they add some value. On the other hand, if you want to completely change/rewrite the application, it would make more sense to maintain your own fork, since you would have full control over it.

**Comment by albacoretuna** [comment]
Ok, I'll fork then. Thanks :)
