### ISSUE TITLE
Set State in every component 

### ISSUE THREAD

**Issue by ajaybeniwal** [romanmatiasko/reti-chess#8]
HI ,

I was working on similar type of game to learn react and flux but i have kept state  in only chessboard component(meaning i have setSstate in only one chessboard component) and I pass data from child components to parent through callbacks and only call setState inside that parent component not inside each component , so I just want to discuss with you that which is better approach for handling state , calling setState in each component or  only just one component

**Comment by romanmatiasko** [comment]
Hi,

I think it depends. There are various ways to handle the state and your approach is completely fine. You can set state on a child component only if your parent and none of the siblings need to know about the state you want to set. Otherwise, you need to set it on the parent. As your application grows you'll be probably passing down a lot of callbacks though.

You can try Flux if you find yourself passing down a lot of callbacks, or you have two unrelated components that need to share the state, or you just think callbacks are not the cleanest approach.

There are also other approaches how to handle the state, i.e. data tree with cursors (check out [Baobab](https://github.com/Yomguithereal/baobab) for example).

Either way, it's up to you which approach you choose. All of them have their pros and cons. I'd say try them out and stick to one you like the most.

**Comment by ajaybeniwal** [comment]
HI,

OfCourse Im using Flux but I am calling action through high level component
and watching the chess store only in high level component.
Anyways thanks for your time I will read out other examples.

Regards,
Ajay Singh

**Comment by romanmatiasko** [comment]
I see, in that case watching for changes only in high level component and passing down the props is fine, but you can call actions from anywhere, there's no need for callbacks.
